### ISSUE TITLE
How can we remark ECN before the flow enters the queue on ifb?

### ISSUE THREAD

**Issue by tomchang21000923** [L4STeam/linux#36]
We created a dualpi2 queue on ifb. How can we remark the download flow to change ECN mark? Because it's already too late to remark in iptables when using ifb. 
In the HTB queue, we can use tc filter rules to direct flows into specific queues. How can we specify flows to go into a classic queue or low-latency queue on dualpi2?

**Comment by minuscat** [comment]
The default identifiers are based on ECT code points, which is done internally in Dualpi2, so no additional tc filters are needed.
Please read the dualpi2 manual ``man tc-dualpi2`` or check the source code to understand how dualpi2 works to mark packets.

Of course, you could use other TCs or iptables to do this, but that's beyond the scope of dualpi2.
I will close the issue here, because it has little to do with this repository.

However, if you can provide detailed setup and problem description, we can further discuss via email.
